version: "3.8"

services:
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mituna_celery_flower
    privileged: true
    group_add: 
      - video
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev:dri:rw
    stdin_open: true
    tty: true
    volumes:
      - /dev/dri:/dev/dri/:rw
      - /var/lib/docker/:/var/lib/docker
    env_file:
      - .env
    environment:
        - TUNA_DB_HOSTNAME=${db_host}
        - TUNA_DB_NAME=${db_name}
        - TUNA_DB_USER_NAME=${db_user}
        - TUNA_DB_USER_PASSWORD=${db_password}
        - BROKER_URL=redis://localhost:6378/14
        - TUNA_REDIS_PORT=6378
    command: "celery -A tuna.celery_app.celery_app flower --debug --persistent=True"
    network_mode: "host"

