version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    expose:
      - "6380"
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    group_add: 
      - video
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev:dri:rw
    stdin_open: true
    tty: true
    volumes:
      - /dev/dri:/dev/dri/:rw
      - /var/lib/docker/:/var/lib/docker
    environment:
        - TUNA_DB_HOSTNAME=${db_hostname}
        - TUNA_DB_NAME=${db_name}
        - TUNA_DB_USER_NAME=${user_name}
        - TUNA_DB_USER_PASSWORD=${user_password}
        - HIP_VISIBLE_DEVICES=1
    env_file:
      - .env
    command: "celery -A tuna.celery_app.celery worker -l info -E"
    depends_on:
      - redis

